name: yme

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_DOMAIN: ${VITE_DOMAIN}
        VITE_APP_NAME: ${VITE_APP_NAME}
        VITE_SOCKET_BASE_URL: ${VITE_SOCKET_BASE_URL}
        VITE_PORT: ${VITE_PORT}
    image: ishnoopy/yme-frontend:latest

# Optional: Add if you're using networks
networks:
  default:
    driver: bridge