name: yme

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${VITE_PORT}:80'
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_DOMAIN=${VITE_DOMAIN}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_SOCKET_BASE_URL=${VITE_SOCKET_BASE_URL}
      - VITE_PORT=${VITE_PORT}
      
    entrypoint: ["/entrypoint.sh"]
